# Generated by Django 6.0.2 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoentry',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photoentry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
