# Generated by Django 6.0.2 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_add_location_name_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoentry',
            name='category',
            field=models.CharField(default='uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='photoentry',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoentry',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoentry',
            name='processing_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='photoentry',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoentry',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
